import { readFileSync, writeFileSync, existsSync } from 'fs';
import path from 'path';
import YAML from 'yaml';
import type { Manifest } from '../types/manifest.js';
import { findProjectRoot } from './paths.js';

const MANIFEST_CANDIDATES = [
  'saascode-kit/manifest.yaml',
  '.saascode/manifest.yaml',
  'manifest.yaml',
  'saascode-kit.yaml',
];

/**
 * Find the manifest file by searching known locations.
 */
export function findManifest(root?: string): string | null {
  const projectRoot = root ?? findProjectRoot();
  for (const candidate of MANIFEST_CANDIDATES) {
    const fullPath = path.join(projectRoot, candidate);
    if (existsSync(fullPath)) return fullPath;
  }
  return null;
}

/**
 * Load and parse the manifest YAML file.
 */
export function loadManifest(manifestPath?: string): Manifest | null {
  const filePath = manifestPath ?? findManifest();
  if (!filePath || !existsSync(filePath)) return null;

  const content = readFileSync(filePath, 'utf-8');
  const parsed = YAML.parse(content) as Manifest;
  return parsed;
}

/**
 * Write a manifest object to a YAML file.
 */
export function writeManifest(manifest: Manifest, outputPath: string): void {
  const content = YAML.stringify(manifest, {
    indent: 2,
    lineWidth: 120,
  });
  writeFileSync(outputPath, `# SaasCode Kit — Manifest\n# Generated by saascode init\n\n${content}`, 'utf-8');
}

/**
 * Get a nested value from the manifest using dot notation.
 * e.g., getManifestValue(manifest, 'stack.backend.framework')
 */
export function getManifestValue(manifest: Manifest, key: string): unknown {
  const parts = key.split('.');
  let current: unknown = manifest;
  for (const part of parts) {
    if (current === null || current === undefined || typeof current !== 'object') return undefined;
    current = (current as Record<string, unknown>)[part];
  }
  return current;
}
