# SaasCode Kit — GitHub Actions Code Review Pipeline
# Runs on every PR: build, test, security scan, pattern check
# Customize paths from manifest.yaml

name: SaasCode Review

on:
  pull_request:
    branches: [main, develop]
  push:
    branches: [main]

env:
  # Set these from manifest.yaml paths
  BACKEND_PATH: "apps/api"         # {{paths.backend}}
  FRONTEND_PATH: "apps/portal"     # {{paths.frontend}}
  API_CLIENT_PATH: "apps/portal/src/lib/api"  # {{paths.api_client}}

jobs:
  # ─── Build & Type Check ───
  build:
    name: Build & TypeScript
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      - run: npm ci

      - name: TypeScript Check
        run: npm run typecheck

      - name: Build Backend
        run: npm --prefix $BACKEND_PATH run build 2>/dev/null || npm run build

      - name: Build Frontend
        run: npm --prefix $FRONTEND_PATH run build 2>/dev/null || npm run build:frontend 2>/dev/null || true

  # ─── Tests ───
  test:
    name: Tests
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"
      - run: npm ci

      - name: Run Tests
        run: npm --prefix $BACKEND_PATH run test 2>/dev/null || npm test

  # ─── Security Scan ───
  security:
    name: Security Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"
      - run: npm ci

      - name: npm Audit
        run: npm audit --audit-level=high
        continue-on-error: true

      - name: Semgrep Scan
        uses: returntocorp/semgrep-action@v1
        with:
          config: .saascode/rules/
        continue-on-error: true

  # ─── Pattern Checks ───
  patterns:
    name: Pattern Verification
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Endpoint Parity Check
        run: |
          echo "=== Frontend API Calls ==="
          if [ -d "$API_CLIENT_PATH" ]; then
            grep -rE "apiClient\.(get|post|patch|delete)" $API_CLIENT_PATH/*.ts 2>/dev/null || echo "(no apiClient calls found)"
          else
            echo "(API client path not found: $API_CLIENT_PATH)"
          fi

          echo ""
          echo "=== Backend Endpoints ==="
          if ls $BACKEND_PATH/src/modules/*/*.controller.ts 1>/dev/null 2>&1; then
            grep -rE "@(Get|Post|Patch|Put|Delete)" $BACKEND_PATH/src/modules/*/*.controller.ts || true
          elif ls $BACKEND_PATH/src/**/*.controller.ts 1>/dev/null 2>&1; then
            grep -rE "@(Get|Post|Patch|Put|Delete)" $BACKEND_PATH/src/**/*.controller.ts || true
          else
            echo "(no controller files found — skipping NestJS-specific check)"
          fi

          echo ""
          echo "Verify each frontend call has a matching backend endpoint."

      # NestJS-specific: Auth Guard Check (only runs if NestJS controllers exist)
      - name: Auth Guard Check
        run: |
          if ! ls $BACKEND_PATH/src/modules/**/*.controller.ts 1>/dev/null 2>&1; then
            echo "SKIPPED: No NestJS controllers found."
            exit 0
          fi

          echo "=== Checking for @Roles without RolesGuard ==="
          ISSUES=$(grep -rn "@Roles(" --include="*.ts" $BACKEND_PATH/src/modules/ 2>/dev/null | while read line; do
            FILE=$(echo "$line" | cut -d: -f1)
            if ! grep -q "RolesGuard" "$FILE"; then
              echo "CRITICAL: $line — Missing RolesGuard!"
            fi
          done)

          if [ -n "$ISSUES" ]; then
            echo "$ISSUES"
            echo ""
            echo "FAILED: @Roles found without RolesGuard. Roles are NOT enforced!"
            exit 1
          else
            echo "PASSED: All @Roles have accompanying RolesGuard."
          fi

      # NestJS-specific: Tenant Isolation Check (only runs if NestJS services exist)
      - name: Tenant Isolation Check
        run: |
          if ! ls $BACKEND_PATH/src/modules/**/*.service.ts 1>/dev/null 2>&1; then
            echo "SKIPPED: No NestJS services found."
            exit 0
          fi

          echo "=== Checking for unscoped queries ==="
          UNSCOPED=$(grep -rn "findMany()" --include="*.service.ts" $BACKEND_PATH/src/modules/ 2>/dev/null | grep -v "tenantId" || true)

          if [ -n "$UNSCOPED" ]; then
            echo "WARNING: Potentially unscoped queries found:"
            echo "$UNSCOPED"
          else
            echo "PASSED: No unscoped findMany() detected."
          fi

      - name: Secrets Check
        run: |
          echo "=== Checking for hardcoded secrets ==="
          SECRETS=""
          [ -d "$BACKEND_PATH/src" ] && SECRETS=$(grep -rn "password\s*=\|secret\s*=\|api[_-]\?key\s*=" --include="*.ts" $BACKEND_PATH/src/ $FRONTEND_PATH/src/ 2>/dev/null | grep -v "process.env\|@Is\|interface\|type \|\.d\.ts" || true)
          [ -z "$SECRETS" ] && [ -d "$FRONTEND_PATH/src" ] && SECRETS=$(grep -rn "password\s*=\|secret\s*=\|api[_-]\?key\s*=" --include="*.ts" $FRONTEND_PATH/src/ 2>/dev/null | grep -v "process.env\|@Is\|interface\|type \|\.d\.ts" || true)

          if [ -n "$SECRETS" ]; then
            echo "WARNING: Possible hardcoded secrets:"
            echo "$SECRETS"
          else
            echo "PASSED: No hardcoded secrets detected."
          fi

      - name: XSS Check
        run: |
          echo "=== Checking for dangerouslySetInnerHTML ==="
          XSS=""
          [ -d "$FRONTEND_PATH/src" ] && XSS=$(grep -rn "dangerouslySetInnerHTML" --include="*.tsx" --include="*.jsx" $FRONTEND_PATH/src/ 2>/dev/null || true)

          if [ -n "$XSS" ]; then
            echo "WARNING: dangerouslySetInnerHTML found:"
            echo "$XSS"
          else
            echo "PASSED: No dangerouslySetInnerHTML detected."
          fi
